
# Netlify build configuration for a Next.js project.
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # The command to build your site.
  command = "npm run build"
  
  # The directory to publish, which contains your built site.
  # For Next.js, this is the .next directory.
  publish = ".next"

# The Netlify Next.js runtime automatically handles server-side rendering,
# API routes, and other Next.js features.
# You may not need a [functions] block if you're using the App Router.
# The runtime will automatically create the necessary functions.
